spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rabbit
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
